version: "2.0"
services:
  elasticsearch:
    #restart: always
    container_name: elasticsearch-log-jenkins
    labels:
      - elasticsearch-log-jenkins
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $PWD/esdata:/usr/share/elasticsearch/data
    #  - $PWD/config:/usr/share/elasticsearch/config
  kibana:
    #restart: always
    container_name: kibana-log-jenkins
    labels:
      - kibana-log-jenkins
    image: kibana
    ports:
      - 5601:5601
    
    environment:
      - ELASTICSEARCH_URL=